# Generated by Django 2.2 on 2020-08-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0002_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('beschreibung', models.TextField(max_length=1000)),
                ('preis', models.CharField(max_length=10)),
                ('images', models.FileField(max_length=254, upload_to='media/')),
            ],
        ),
    ]
