# Generated by Django 2.2 on 2020-08-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_uploadimagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
