# Generated by Django 2.2 on 2020-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200823_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagemodel',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
