# Generated by Django 2.2 on 2020-09-08 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_sample'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
